# Generated by Django 4.0.1 on 2022-03-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='madhan',
            name='place',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
