# Generated by Django 4.0.1 on 2022-04-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp2', '0008_category_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
